// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjgZwwfsCNKR5YbDD50UgE9qLoqVqLj9A',
    appId: '1:447482014567:web:1a239f40e19596eda49dc2',
    messagingSenderId: '447482014567',
    projectId: 'test-login3-3e77d',
    authDomain: 'test-login3-3e77d.firebaseapp.com',
    storageBucket: 'test-login3-3e77d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHuQJEnTzrogr87uQ28nzIfiqeB2xa95s',
    appId: '1:447482014567:android:f42f9100c7598163a49dc2',
    messagingSenderId: '447482014567',
    projectId: 'test-login3-3e77d',
    storageBucket: 'test-login3-3e77d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMdclOnXXCUf7KjTkf6SU244m2YZJEQB4',
    appId: '1:447482014567:ios:b78e3ce1f2a31b6aa49dc2',
    messagingSenderId: '447482014567',
    projectId: 'test-login3-3e77d',
    storageBucket: 'test-login3-3e77d.firebasestorage.app',
    iosBundleId: 'com.example.repaso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMdclOnXXCUf7KjTkf6SU244m2YZJEQB4',
    appId: '1:447482014567:ios:b78e3ce1f2a31b6aa49dc2',
    messagingSenderId: '447482014567',
    projectId: 'test-login3-3e77d',
    storageBucket: 'test-login3-3e77d.firebasestorage.app',
    iosBundleId: 'com.example.repaso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjgZwwfsCNKR5YbDD50UgE9qLoqVqLj9A',
    appId: '1:447482014567:web:47e0c0864665e1bfa49dc2',
    messagingSenderId: '447482014567',
    projectId: 'test-login3-3e77d',
    authDomain: 'test-login3-3e77d.firebaseapp.com',
    storageBucket: 'test-login3-3e77d.firebasestorage.app',
  );
}
